### ISSUE TITLE
Could There Be an Issue with the Stage 2 Loss in Your Paper?

### ISSUE THREAD

**Issue by brian29688071** [alviur/pocon_wacv2024#1]
In your paper, on page 4 under section 3.3 'Plasticity-Optimized Complementary Networks', the description of the loss equation for Stage 2 indicates that gφ is fed into n(the adaptation projector). This seems to be inconsistent with the diagram provided. Could you please clarify?

**Comment by alviur** [comment]
Hi,

Indeed, equation 3 has a typo. The correct approach follows Fig.1 (step 2) as in the paragraph text : 

"Projector _n_ maps the embedding space from the main network _f_ θ to the embedding space learned in the expert network gϕ."

To replicate, just use a projector in the output of _f_ as in the retrospection part of the method.

I will correct the equation and upload a revised version. 

Thanks!

Alex
