### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by JAYATEJAK** [alviur/pocon_wacv2024#3]
Hi @alviur , when will the source code be available?

**Comment by alviur** [comment]
Hi,

I am planning to release it at the end of next week (check on February 5th).

**Comment by schuy1er** [comment]
Hi @alviur , sorry to disturb but when will the source code be available?

**Comment by alviur** [comment]
Hi,

I uploaded the code using the [FACIL ](https://github.com/mmasana/FACIL)framework. I am moving the code to work inside the CaSSLe framework (which I think is more straightforward for benchmarking purposes against PFR and CaSSLe); however, it will take time. The current code works for CIFAR100, but it is extremely slow for TinyImagenet and ImageNet100.
